# Generated by Django 5.2.1 on 2025-05-14 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_code', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('approved_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_form_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('warehouse_location', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=255)),
                ('prepared_by', models.CharField(max_length=100)),
                ('transporter_name', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('checked_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('approval_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hello.goodsrelease')),
            ],
        ),
    ]
